version: '3.7'

services:
  sample:
    container_name: sample
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
# version: '3.7'

# services:
#   sample:
#     container_name: sample
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - '.:/app'
#       - '/app/node_modules'
#     ports:
#       - 3000:3000
#     stdin_open: true
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#       command: npm start
